#!/bin/sh
if [ "$#" -eq  0 ]
then
echo "Usage ./ugen_lookup NAME"
exit 1
fi

NAME=$1

REF=/usr/local/share/sporth/ugen_reference.txt

if [ ! -f ]
then
echo "$REF does not exist!"
exit 1
fi

LINES=$(grep -r -n "^Name:" $REF | egrep "$NAME" | cut -d ':' -f 1 | sed "s/\n/ /g")

if [ -z "$LINES" ]
then
echo "Could not find entry $NAME"
exit 1
fi

for START in $LINES
do
END=$(echo "$START + 3" | bc)
sed -n "$START,$END P" $REF
echo
done
