#!/bin/sh

if [ "$#" -eq 0 ]
then
    echo "Usage: faust2sporth file.dsp"
    exit
fi

NAME=${1%.dsp}
CPP_FILE=$NAME.cpp
DSP_FILE=$NAME.dsp
SO_FILE=$NAME.so

faust -cn $NAME -uim -o $CPP_FILE -a sporth.cpp $DSP_FILE
g++ -g -fPIC -I/usr/local/include -shared $CPP_FILE -o $SO_FILE -lsporth
rm $CPP_FILE
