/* These *must* be in the same order as they appear in flist.h */
enum {
SPORTH_ADD = SPORTH_FOFFSET,
SPORTH_SUB,
SPORTH_MUL,
SPORTH_DIV,
SPORTH_SINE,
SPORTH_CONSTANT,
SPORTH_MIX,
SPORTH_METRO,
SPORTH_TENV,
SPORTH_FM,
SPORTH_MTOF,
SPORTH_DUP,
SPORTH_SWAP,
SPORTH_DROP,
SPORTH_REVSC,
SPORTH_GEN_SINE,
SPORTH_OSC
};
